#pragma once
// サウンド機能の有効/無効
#define ENABLE_SOUND
// メッシュ機能の有効/無効
//#define ENABLE_MESH
// スプライト機能の有効/無効
#define ENABLE_SPRITE
// フォント機能の有効/無効
#define ENABLE_FONT
// Effekseerによるエフェクト機能の有効/無効
//#define ENABLE_EFFEKSEER
// 視覚効果(ポストエフェクト)機能の有効/無効
#define ENABLE_VISUAL_EFFECT

// フラグマネージャーで管理されるbool型を有効/無効
#define ENABLE_CLASS_BOOL
// ファイルに関する機能の有効/無効
#define ENABLE_FILE
// 色に関する機能の有効/無効
#define ENABLE_COLOR
// 数式に関する機能の有効/無効
#define ENABLE_MATH
// 物理挙動に関する機能の有効/無効
#define ENABLE_PHYSICS
// 文字変換に関する機能の有効/無効
#define ENABLE_STRING_CONVERSION
// イージングに関する機能の有効/無効
#define ENABLE_EASING
// アニメーションに関する機能の有効/無効
#define ENABLE_ANIMATION
// オブザーバーに関する機能の有効/無効
//#define ENABLE_OBSERVER
// スレッドに関する機能の有効/無効
#define ENABLE_THREAD
// ネットワーク通信(ローカル/オンライン)に関する機能の有効/無効
//#define ENABLE_NETWORK
// 定数に関する機能の有効/無効
#define ENABLE_CONST
// マスターデータに関する機能の有効/無効
#define ENABLE_MASTER_DATA
// キャッシュデータに関する機能の有効/無効
//#define ENABLE_CASH
// 時間に関する機能の有効/無効
#define ENABLE_TIME

// Windowsのウィンドウに関する機能の有効/無効
#define ENABLE_WINDOWS_WINDOW
// Windowsのオーディオデバイスに関する機能の有効/無効
#define ENABLE_WINDOWS_AUDIO_DEVICE
// Windowsのメニューに関する機能の有効/無効
#define ENABLE_WINDOWS_MENU
// Windowsのタスクトレイに関する機能の有効/無効
#define ENABLE_WINDOWS_TASK_TRAY
// Windowsのショートカットに関する機能の有効/無効
#define ENABLE_WINDOWS_SHORT_CUT

// 透明ウィンドウの有効/無効
#define ENABLE_TRANSPARENT_WINDOW
// サブウィンドウの有効/無効
#define ENABLE_SUB_WINDOW
