#pragma once
// サウンド機能の有効/無効
#define ENABLE_SOUND
// メッシュ機能の有効/無効
//#define ENABLE_MESH
// スプライト機能の有効/無効
#define ENABLE_SPRITE
// フォント機能の有効/無効
#define ENABLE_FONT
// フォグ機能の有効/無効
//#define ENABLE_FOG
// Effekseerによるエフェクト機能の有効/無効
//#define ENABLE_EFFEKSEER

// フラグマネージャーで管理されるbool型を有効/無効
#define ENABLE_CLASS_BOOL
// ファイルに関する機能の有効/無効
#define ENABLE_FILE
// 色に関する機能の有効/無効
#define ENABLE_COLOR
// イージングに関する機能の有効/無効
#define ENABLE_EASING
// アニメーションに関する機能の有効/無効
#define ENABLE_ANIMATION
// メッセージ機能の有効/無効
#define ENABLE_MESSAGE
// 文字変換に関する機能の有効/無効
#define ENABLE_STRING_CONVERSION
// 定数に関する機能の有効/無効
#define ENABLE_CONST
// オブザーバーに関する機能の有効/無効
#define ENABLE_OBSERVER
// マスターデータに関する機能の有効/無効
#define ENABLE_MASTER_DATA
// キャッシュデータに関する機能の有効/無効
#define ENABLE_CASH
// 時間に関する機能の有効/無効
#define ENABLE_TIME
// Windowsのウィンドウに関する機能の有効/無効
#define ENABLE_WINDOWS_WINDOW
// Windowsのオーディオデバイスに関する機能の有効/無効
#define ENABLE_WINDOWS_AUDIO_DEVICE
// Windowsのメニューに関する機能の有効/無効
#define ENABLE_WINDOWS_MENU
// Windowsのタスクトレイに関する機能の有効/無効
#define ENABLE_WINDOWS_TASK_TRAY

// 透明ウィンドウの有効/無効
#define ENABLE_TRANSPARENT_WINDOW
// サブウィンドウの有効/無効
#define ENABLE_SUB_WINDOW